// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanOfStudy.Models;

#nullable disable

namespace PlanOfStudy.Migrations
{
    [DbContext(typeof(POSDbContext))]
    [Migration("20230405210950_SavedPlans")]
    partial class SavedPlans
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PlanOfStudy.Models.Course", b =>
                {
                    b.Property<long?>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("CourseID"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Credits")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("PlanOfStudy.Models.PlanLine", b =>
                {
                    b.Property<int>("PlanLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanLineID"), 1L, 1);

                    b.Property<long>("CourseID")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SavedPlanID")
                        .HasColumnType("int");

                    b.HasKey("PlanLineID");

                    b.HasIndex("CourseID");

                    b.HasIndex("SavedPlanID");

                    b.ToTable("PlanLine");
                });

            modelBuilder.Entity("PlanOfStudy.Models.SavedPlan", b =>
                {
                    b.Property<int>("SavedPlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SavedPlanID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SavedPlanID");

                    b.ToTable("SavedPlans");
                });

            modelBuilder.Entity("PlanOfStudy.Models.PlanLine", b =>
                {
                    b.HasOne("PlanOfStudy.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanOfStudy.Models.SavedPlan", null)
                        .WithMany("Lines")
                        .HasForeignKey("SavedPlanID");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("PlanOfStudy.Models.SavedPlan", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
